import React, {Component} from 'react';
import {Tabs, Tab, Grid, Cell, Card, CardText, CardTitle, CardActions, CardMenu, Button, IconButton} from 'react-mdl' ;
import '../../css/components/portfolio.css';


class Portfolio extends Component {
  constructor(props){
    super(props);
    this.state = { activeTab: 0 };
  }

  toggleCategories(){
    if(this.state.activeTab === 0){
      return (
        <div className="projects-grid">
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#fff', height: '176px',
            background: 'url(https://create-react-app.dev/img/logo-og.png) center / cover'
          }}>
            React for Fun
          </CardTitle>
          <CardText>
            Project made when learning React. Contains some easy pages, games and calculator.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/react_fun">GitHub</a></Button>
            <Button colored><a href="https://kamilabartnik.github.io/react_fun/">GitHub Pages</a></Button>
          </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#fff', height: '176px',
            background: 'url(https://create-react-app.dev/img/logo-og.png) center / cover'
          }}>
            Admin site project
          </CardTitle>
          <CardText>
            Project made with Udemy course: The Complete Full-Stack JavaScript Course.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/react">GitHub</a></Button>
           </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        </div>
      )
    } else if(this.state.activeTab === 1){
      return(
        <div className="projects-grid">
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#000', height: '176px',
            background: 'url(https://cdn.auth0.com/blog/logos/vuejs-logo.png) center / cover'
          }}>
            Learning VueJS with Max
          </CardTitle>
          <CardText>
            Project made with Udemy course by Maximilian Schwarzmüller.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/maxvue">GitHub</a></Button>
          </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#000', height: '176px',
            background: 'url(https://cdn.auth0.com/blog/logos/vuejs-logo.png) center / cover'
          }}>
            Quiz generator
          </CardTitle>
          <CardText>
            Questions generated by opendb and showed with site made with VueJS.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/quizVue">GitHub</a></Button>
           </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        </div>
      )
    } else if(this.state.activeTab === 2){
      return(
        <div className="projects-grid">
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#fff', height: '176px',
            background: 'url(https://i.udemycdn.com/course/750x422/792484_cc98_3.jpg) center / cover'
          }}>
            Liga Terraformacji Marsa
          </CardTitle>
          <CardText>
            Site for Poznan Terraforming Mars League.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/terraformacja">GitHub</a></Button>
            <Button colored><a href="https://kamilabartnik.github.io/terraformacja/">GitHub Pages</a></Button>
          </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        <Card shadow={5} style={{ minWidth: '450', margin: 'auto' }}>
          <CardTitle style={{
            color: '#fff', height: '176px',
            background: 'url(https://i.udemycdn.com/course/750x422/792484_cc98_3.jpg) center / cover'
          }}>
            Kamila Bartnik CV
          </CardTitle>
          <CardText>
            Former CV.
          </CardText>
          <CardActions border>
            <Button colored><a href="https://github.com/kamilabartnik/kamilabartnik.github.io">GitHub</a></Button>
            <Button colored><a href="https://kamilabartnik.github.io/">GitHub Pages</a></Button>
          </CardActions>
          <CardMenu style={{ color: '#fff' }}>
            <IconButton name="share" />
          </CardMenu>
        </Card>
        </div>
      )
    }
  }

  render() {
    return (
      <div className="category-tabs">
        <Tabs activeTab={this.state.activeTab} onChange={(tabId) => this.setState({activeTab: tabId})} ripple>
          <Tab>React</Tab>
          <Tab>VueJS</Tab>
          <Tab>HTML/CSS with VanillaJS</Tab>
        </Tabs>

          <Grid>
            <Cell col={12}>
              <div className="content">{this.toggleCategories()}</div>
            </Cell>
          </Grid>
          
      </div>
    )
  }
}

export default Portfolio;